### ISSUE TITLE
Is it possible to add column?

### ISSUE THREAD

**Issue by teertinker** [vkaravir/bib-publication-list#10]
Hello,
this tool is really great. I wonder if its possible to ad a column to the table and insert some new data (by manipulating the code).

I would like to add the Keywords of my bibtexfile to another column.

I thought this might work by editing the code by adding the italic code, but it doesn't work.

bibentries.push([item.year, *item.keywords*, bib2html.labels[item.entryType], html]); 
....
var table = this.$pubTable.dataTable({ 'aaData': bibentries,
                              'aaSorting': this.options.sorting,
                              'aoColumns': [ { "sTitle": "Year"},
                                                    *{ "sTitle": "Keywords"},*
                                             { "sTitle": "Type", "sType": "type-sort", "asSorting": [ "desc", "asc" ]},
                                             { "sTitle": "Publication", "bSortable": false }],
                              'bPaginate': false
                            });

Is there a way I could achieve 4 columns?

**Comment by vkaravir** [comment]
That's how it should be work. Two possible reasons for it not working come to mind:

 * Do all the items have keywords? If not, you might want to replace ```item.keywords``` with ```item.keywords || ""```.
 * Did you build the code again after editing? Or did you edit directly the ```build/biblist.js``` (or the min version)?

**Comment by teertinker** [comment]
Dear vkaravir,
thanks a lot. The first hint did it. (I edited the bib-list.js directly).

**Comment by vkaravir** [comment]
Cool that it worked! I might add support for custom columns in the future, but it might take me a while to get to it :)
