### ISSUE TITLE
Uncaught ReferenceError: bibdownloaded is not defined

### ISSUE THREAD

**Issue by joydeep-b** [vkaravir/bib-publication-list#13]
Line 2834 of bib-list.js references an undefined function, "bibdownloaded()"

**Comment by vkaravir** [comment]
Hi!
Are you sure you're using the latest version? This was fixed already in #8 over a year ago :)

**Comment by joydeep-b** [comment]
So it is! Sorry for the duplicate report, I was testing with the version on
your website (http://villekaravirta.com/publications/), which still has the
old version. :)
Great job on this library, by the way, especially with the simplicity of
setup!

**Comment by vkaravir** [comment]
Good point about my website not using the latest version :) Updated there as well now. Thanks!
