### ISSUE TITLE
New browser tab for links and spacing adjustment between search input

### ISSUE THREAD

**Issue by RohanAsmat** [vkaravir/bib-publication-list#20]
#19 

Normally as a user while looking at your research contribution, I would like to open number of research artifacts at the same time and would not want to loose the context of the index page where the contributions are listed. Hence, it is better to open up a new browser tab for each research artifact.

The search input seemed a bit messy, I think equal spacing from bottom and top would make it more neater visually.

**Comment by vkaravir** [comment]
Good ideas, thank you for the pull request!
