### ISSUE TITLE
Visualisation not visible with many bibtex entries

### ISSUE THREAD

**Issue by robstewart57** [vkaravir/bib-publication-list#22]
Hi,

This is great software, thanks for sharing!

I'm adopting it for a research group. There are 457 entries in the bibtex file for all publications within the group. Here is the bibtex file:

http://www.macs.hw.ac.uk/~dsg/dblp2bibtex/dsg-publications.bib

The bib-publication-list visualisation isn't visible for this bibtex file:

http://www.macs.hw.ac.uk/~dsg/wp/?page_id=1278

If I zoom into the web page, I can faintly see a few colours in the visualisation, though the colours aren't clear and the bars for book/journal/article/ etc.. are very thin.

Is there anything I can do, to make the visualisation: the colours, and distinguishing the types of publications, clear without zooming into the visualisation?

Thanks!

**Comment by vkaravir** [comment]
This should now be fixed. Let me know if you still have the issue.

**Comment by robstewart57** [comment]
@vkaravir Great, thanks!

Indeed, e4b9c25685f0ee09a1731bb19ced9e1c767bb71f fixes the visualisation on the page:

http://www.macs.hw.ac.uk/~dsg/wp/?page_id=1278

**Comment by ihnorton** [comment]
The solid bars were a very nice change, thank you! One thing I added was displaying the total count below year:

![image](https://user-images.githubusercontent.com/327706/36061908-e22e6012-0e2f-11e8-8976-d7827851cb31.png)

It's a little hacky, but here's the diff in case it is of interest:

```
diff --git a/bib-publication-list.css b/bib-publication-list.css
index dbc3e3e..d5958d9 100755
--- a/bib-publication-list.css
+++ b/bib-publication-list.css
@@ -1,9 +1,9 @@
 span.undefined { color:red; }
 .bibtable {width:100%; margin: 0 auto; clear: both;}
-.bibchart { width: 100%; height: 100px; margin-bottom: 20px;}
+.bibchart { width: 100%; height: 100px; margin-bottom: 40px;}
 .clear {clear:both;}
 .year { position: relative; height: 100%; border-bottom: 1px solid black; display: inline-block;}
-.yearlabel { position: absolute; bottom: -20px; text-align: center; width: 100%; font-size: smaller;}
+.yearlabel { position: absolute; bottom: -40px; text-align: center; width: 100%; font-size: smaller;}
 .pub { border: 1px solid white; background-color: #eee; }
 .inproceedings { background-color: #ccf; }
 .article { background-color: #beb; }
diff --git a/src/bib-publication-list.js b/src/bib-publication-list.js
index a1d59e1..b6c2ef0 100755
--- a/src/bib-publication-list.js
+++ b/src/bib-publication-list.js
@@ -394,7 +394,7 @@ var bibtexify = (function($) {
             }
             str += itemStr;

-            return str + '<div class="yearlabel">' + item.year + '</div></div>';
+            return str + '<div class="yearlabel">' + item.year + ' (' + item.count + ')' + '</div></div>';
         };
         var statsHtml = '<style>' + styleStr + '</style>';
         yearstats.forEach(function(item) {
```
